server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dailyschedule
    username: dailyschedule
    password: wnsdud12!

  devtools:
    remote:
      restart:
        enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true